name: CI

on:
  push:
    branches:
      - develop
    paths:
      - src/**
      - package.json
      - .node-version
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
              npm install
      - name: Build
        run: |
              npm run build
      - name: Test
        run: |
              npm run test

  tag:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              set -x
              git config user.name "GitHub Actions"
              git config user.email "actions@github.com"
              npm version patch
              # git add package.json package-lock.json
              # git commit -m "Bump version to $(node -p "require('./package.json').version") [skip ci]"
              git push origin develop --tags

  publish-npm:
    needs: [tag]
    runs-on: ubuntu-latest
    concurrency: publish
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
              npm ci
              npm run build
              npm publish --access public --provenance

  publish-github:
    needs: [tag]
    runs-on: ubuntu-latest
    concurrency: publish
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: |
              npm ci
      - name: Publish to GitHub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              npm publish

  notify:
    needs: [tag]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: horology-web
    steps:
      - uses: juztcode/repo-ditpatch-action@v1
        continue-on-error: true
        with:
          event-type: core-published
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: pilgrimagesoftware/${{ matrix.repo }}
